version: '2'
services:
  cacti:
    #image: domezy/cacti:0.8.8b-fpm-alpine
    image: extvos/cacti
    container_name: cacti
    links:
      - mysql
    ports:
      - "161:161"  #BIND SMTP PORT TO HOST
      - "9012:80"            #BIND HTTP PORT TO HOST
    volumes:
      - ./docker/configurations/cacti/global.php:/opt/cacti/include/global.php
      - ./docker/configurations/cacti/global.php:/opt/cacti/include/config.php
    networks:
      - app_net_1
    #env_file: .env.cacti
    restart: always

  mysql:
    image: mysql:5.6
    container_name: mysql
    command: --sql-mode=NO_ENGINE_SUBSTITUTION
    volumes:
      - ./mysql:/var/lib/mysql  #STORE MYSQL DATA INTO HOST FOLDER
      - ./cacti-0.8.8f.sql:/docker-entrypoint-initdb.d/cacti.sql #IMPORT CACTI EMPITY SQL IN MYSQL DB
    networks:
      - app_net_1
    env_file: .env.mysql
    restart: always

networks:
   app_net_1:
     driver: bridge
     ipam:
      driver: default
      config:
      - subnet: 10.100.3.0/24
        ip_range: 10.100.3.2/24
